/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    '../../node_modules/flowbite-react/lib/esm/**/*.js'
  ],
  theme: {
    extend: {},
  },
  plugins: [
    require('flowbite/plugin')
  ],
  safelist: [
    'gap-2',
    'z-0',
    'justify-start',
    'pl-4',
    'border-b-2',
    'border-white-100',
    'h-[64px]',
    'flex',
    'border',
    'rounded-sm',
    'border-transparent',
    'shadow-none',
    'focus:border-blue-500',
    'hover:bg-gray-100',
    'hover:border-transparent',
    'flex-grow',
    'text-sm',
    'css-14qglws',
    'font-semibold',
    'text-gray-600',
    'border-gray-300',
    'rounded-lg',
    'bg-white',
    'mb-2',
    'mt-4',
    'px-1',
    'pl-2',
    'ml-2',
    'py-2',
    'm-1',
    'p-5',
    'shadow-sm',
    '[&.selected]:w-1/4',
    'h-[calc(100%-64px)]',
    '[&.selected]:px-2',
    'absolute right-0 top-8 gap-1 z-10',
    'z-0',
    'relative',
    'group',
    'text-center',
    'mb-5',
    'overflow-y-auto',
    'w-full',
    'scrollbar',
    'flex-col',
    'px-3',
    'py-3',
    'h-full',
    'absolute', 'inset-0', 'flex', 'items-center', 'justify-center', 'opacity-0', 'group-hover:opacity-100', 'transition-opacity', 'duration-300', 'bg-gray-600', 'bg-opacity-50', 'rounded-full', 'cursor-pointer'
  ],
}
